"""Auto-generated Moonraker API bindings — DO NOT EDIT.

Generated by scripts/generate_bindings.py at 2026-02-25T21:14:47Z
from schema/moonraker_api.yaml.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pymoonraker.client import MoonrakerClient


class PrinterNamespace:
    """Klipper printer administration

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def info(self) -> Any:
        """Get Klipper host information (state, hostname, versions)
        """
        return await self._client.call("printer.info")

    async def emergency_stop(self) -> str:
        """Immediately halt the printer
        """
        return await self._client.call("printer.emergency_stop")

    async def restart(self) -> str:
        """Soft-restart Klipper host software
        """
        return await self._client.call("printer.restart")

    async def firmware_restart(self) -> str:
        """Restart Klipper via firmware restart (MCU reset)
        """
        return await self._client.call("printer.firmware_restart")

    async def gcode_script(self, script: str) -> str:
        """Execute a G-code script

        Args:
            script: G-code to execute
        """
        params: dict[str, Any] = {}
        params["script"] = script
        return await self._client.call("printer.gcode.script", params)

    async def gcode_help(self) -> dict[str, str]:
        """List all available G-code commands with descriptions
        """
        return await self._client.call("printer.gcode.help")

    async def objects_list(self) -> Any:
        """List all available printer objects
        """
        return await self._client.call("printer.objects.list")

    async def objects_query(self, objects: dict[str, list[str] | None]) -> dict[str, Any]:
        """Query printer object status

        Args:
            objects: Mapping of object name to list of fields (or None for all fields)
        """
        params: dict[str, Any] = {}
        params["objects"] = objects
        return await self._client.call("printer.objects.query", params)

    async def objects_subscribe(self, objects: dict[str, list[str] | None]) -> dict[str, Any]:
        """Subscribe to printer object status updates

        Args:
            objects: Objects and fields to subscribe to
        """
        params: dict[str, Any] = {}
        params["objects"] = objects
        return await self._client.call("printer.objects.subscribe", params)

    async def print_start(self, filename: str) -> str:
        """Start printing a file

        Args:
            filename: Path to the G-code file to print
        """
        params: dict[str, Any] = {}
        params["filename"] = filename
        return await self._client.call("printer.print.start", params)

    async def print_pause(self) -> str:
        """Pause the current print
        """
        return await self._client.call("printer.print.pause")

    async def print_resume(self) -> str:
        """Resume a paused print
        """
        return await self._client.call("printer.print.resume")

    async def print_cancel(self) -> str:
        """Cancel the current print
        """
        return await self._client.call("printer.print.cancel")

class ServerNamespace:
    """Moonraker server administration

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def info(self) -> Any:
        """Get Moonraker server information
        """
        return await self._client.call("server.info")

    async def config(self) -> dict[str, Any]:
        """Get the full Moonraker configuration
        """
        return await self._client.call("server.config")

    async def temperature_store(self, include_monitors: bool | None = None) -> dict[str, Any]:
        """Get cached temperature history

        Args:
            include_monitors: Include temperature monitors in the response
        """
        params: dict[str, Any] = {}
        if include_monitors is not None:
            params["include_monitors"] = include_monitors
        return await self._client.call("server.temperature_store", params)

    async def gcode_store(self, count: int | None = None) -> dict[str, Any]:
        """Get cached G-code console responses

        Args:
            count: Number of responses to return
        """
        params: dict[str, Any] = {}
        if count is not None:
            params["count"] = count
        return await self._client.call("server.gcode_store", params)

    async def restart(self) -> str:
        """Restart the Moonraker server
        """
        return await self._client.call("server.restart")

    async def connection_identify(self, client_name: str, version: str, type: str, url: str) -> Any:
        """Identify this client connection to the server

        Args:
            client_name: Name of the client application
            version: Client version string
            type: Client type: web, desktop, mobile, agent, other
            url: Client homepage or repository URL
        """
        params: dict[str, Any] = {}
        params["client_name"] = client_name
        params["version"] = version
        params["type"] = type
        params["url"] = url
        return await self._client.call("server.connection.identify", params)

class FilesNamespace:
    """File and directory management

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def list(self, root: str | None = None) -> list[dict[str, Any]]:
        """List files in a root directory

        Args:
            root: Root directory (default: gcodes)
        """
        params: dict[str, Any] = {}
        if root is not None:
            params["root"] = root
        return await self._client.call("server.files.list", params)

    async def roots(self) -> list[dict[str, Any]]:
        """List all registered file root directories
        """
        return await self._client.call("server.files.roots")

    async def metadata(self, filename: str) -> Any:
        """Get detailed metadata for a G-code file

        Args:
            filename: Path to the file relative to its root
        """
        params: dict[str, Any] = {}
        params["filename"] = filename
        return await self._client.call("server.files.metadata", params)

    async def create_directory(self, path: str) -> dict[str, Any]:
        """Create a new directory

        Args:
            path: Directory path to create
        """
        params: dict[str, Any] = {}
        params["path"] = path
        return await self._client.call("server.files.directory", params)

    async def delete_directory(self, path: str, force: bool | None = None) -> dict[str, Any]:
        """Delete a directory

        Args:
            path: Directory path to delete
            force: Force delete non-empty directory
        """
        params: dict[str, Any] = {}
        params["path"] = path
        if force is not None:
            params["force"] = force
        return await self._client.call("server.files.delete_directory", params)

    async def move(self, source: str, dest: str) -> dict[str, Any]:
        """Move or rename a file or directory

        Args:
            source: Source path
            dest: Destination path
        """
        params: dict[str, Any] = {}
        params["source"] = source
        params["dest"] = dest
        return await self._client.call("server.files.move", params)

    async def copy(self, source: str, dest: str) -> dict[str, Any]:
        """Copy a file or directory

        Args:
            source: Source path
            dest: Destination path
        """
        params: dict[str, Any] = {}
        params["source"] = source
        params["dest"] = dest
        return await self._client.call("server.files.copy", params)

    async def delete_file(self, root: str, path: str) -> dict[str, Any]:
        """Delete a file

        Args:
            root: File root
            path: File path relative to root
        """
        params: dict[str, Any] = {}
        params["root"] = root
        params["path"] = path
        return await self._client.call("server.files.delete_file", params)

class JobQueueNamespace:
    """Print job queue management

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def status(self) -> Any:
        """Get job queue status and queued jobs
        """
        return await self._client.call("server.job_queue.status")

    async def enqueue(self, filenames: list[str]) -> Any:
        """Add one or more jobs to the queue

        Args:
            filenames: List of filenames to enqueue
        """
        params: dict[str, Any] = {}
        params["filenames"] = filenames
        return await self._client.call("server.job_queue.post_job", params)

    async def delete(self, job_ids: list[str]) -> Any:
        """Remove jobs from the queue

        Args:
            job_ids: List of job IDs to remove
        """
        params: dict[str, Any] = {}
        params["job_ids"] = job_ids
        return await self._client.call("server.job_queue.delete_job", params)

    async def pause(self) -> Any:
        """Pause the job queue
        """
        return await self._client.call("server.job_queue.pause")

    async def start(self) -> Any:
        """Start or resume the job queue
        """
        return await self._client.call("server.job_queue.start")

class HistoryNamespace:
    """Print history

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def list(self, limit: int | None = None, start: int | None = None, since: float | None = None, before: float | None = None, order: str | None = None) -> dict[str, Any]:
        """List job history entries

        Args:
            limit: Maximum number of entries to return
            start: Starting index
            since: Unix timestamp; only return jobs after this time
            before: Unix timestamp; only return jobs before this time
            order: Sort order: asc or desc
        """
        params: dict[str, Any] = {}
        if limit is not None:
            params["limit"] = limit
        if start is not None:
            params["start"] = start
        if since is not None:
            params["since"] = since
        if before is not None:
            params["before"] = before
        if order is not None:
            params["order"] = order
        return await self._client.call("server.history.list", params)

    async def totals(self) -> Any:
        """Get aggregate print statistics
        """
        return await self._client.call("server.history.totals")

    async def get_job(self, uid: str) -> Any:
        """Get details of a single history job

        Args:
            uid: Job ID
        """
        params: dict[str, Any] = {}
        params["uid"] = uid
        return await self._client.call("server.history.get_job", params)

    async def delete_job(self, uid: str) -> list[str]:
        """Delete a history entry

        Args:
            uid: Job ID to delete
        """
        params: dict[str, Any] = {}
        params["uid"] = uid
        return await self._client.call("server.history.delete_job", params)

class MachineNamespace:
    """Host machine administration

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def system_info(self) -> dict[str, Any]:
        """Get host system information (CPU, distro, network)
        """
        return await self._client.call("machine.system_info")

    async def shutdown(self) -> str:
        """Shut down the host machine
        """
        return await self._client.call("machine.shutdown")

    async def reboot(self) -> str:
        """Reboot the host machine
        """
        return await self._client.call("machine.reboot")

    async def proc_stats(self) -> dict[str, Any]:
        """Get process statistics for Moonraker and system
        """
        return await self._client.call("machine.proc_stats")

    async def restart_service(self, service: str) -> str:
        """Restart a systemd service

        Args:
            service: Service name to restart
        """
        params: dict[str, Any] = {}
        params["service"] = service
        return await self._client.call("machine.services.restart", params)

    async def stop_service(self, service: str) -> str:
        """Stop a systemd service

        Args:
            service: Service name to stop
        """
        params: dict[str, Any] = {}
        params["service"] = service
        return await self._client.call("machine.services.stop", params)

    async def start_service(self, service: str) -> str:
        """Start a systemd service

        Args:
            service: Service name to start
        """
        params: dict[str, Any] = {}
        params["service"] = service
        return await self._client.call("machine.services.start", params)

class UpdateManagerNamespace:
    """Software update management

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def status(self, refresh: bool | None = None) -> dict[str, Any]:
        """Get update status for all tracked software

        Args:
            refresh: Refresh update state from remote
        """
        params: dict[str, Any] = {}
        if refresh is not None:
            params["refresh"] = refresh
        return await self._client.call("machine.update.status", params)

    async def refresh(self) -> dict[str, Any]:
        """Force refresh of update state from remote
        """
        return await self._client.call("machine.update.refresh")

class PowerNamespace:
    """Power device control

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def devices(self) -> dict[str, Any]:
        """List all configured power devices
        """
        return await self._client.call("machine.device_power.devices")

    async def get_device(self, device: str) -> dict[str, str]:
        """Get power state of a device

        Args:
            device: Device name
        """
        params: dict[str, Any] = {}
        params["device"] = device
        return await self._client.call("machine.device_power.get_device", params)

    async def set_device(self, device: str, action: str) -> dict[str, str]:
        """Set power state of a device

        Args:
            device: Device name
            action: Action: on, off, or toggle
        """
        params: dict[str, Any] = {}
        params["device"] = device
        params["action"] = action
        return await self._client.call("machine.device_power.post_device", params)

class AccessNamespace:
    """User authentication and API key management

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def login(self, username: str, password: str) -> dict[str, Any]:
        """Authenticate with username and password

        Args:
            username: Username
            password: Password
        """
        params: dict[str, Any] = {}
        params["username"] = username
        params["password"] = password
        return await self._client.call("access.login", params)

    async def logout(self) -> dict[str, Any]:
        """Invalidate current session
        """
        return await self._client.call("access.logout")

    async def get_user(self) -> dict[str, Any]:
        """Get current authenticated user info
        """
        return await self._client.call("access.get_user")

    async def list_users(self) -> dict[str, Any]:
        """List all registered users
        """
        return await self._client.call("access.users.list")

    async def refresh_jwt(self, refresh_token: str) -> dict[str, Any]:
        """Refresh an expired JWT access token

        Args:
            refresh_token: Refresh token from login
        """
        params: dict[str, Any] = {}
        params["refresh_token"] = refresh_token
        return await self._client.call("access.refresh_jwt", params)

    async def get_api_key(self) -> str:
        """Get the current API key
        """
        return await self._client.call("access.api_key")

    async def oneshot_token(self) -> str:
        """Generate a single-use authentication token
        """
        return await self._client.call("access.oneshot_token")

class DatabaseNamespace:
    """Moonraker key-value database

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def list_namespaces(self) -> dict[str, Any]:
        """List all database namespaces
        """
        return await self._client.call("server.database.list")

    async def get_item(self, namespace: str, key: str | None = None) -> Any:
        """Retrieve a value from the database

        Args:
            namespace: Database namespace
            key: Key to retrieve (omit for full namespace)
        """
        params: dict[str, Any] = {}
        params["namespace"] = namespace
        if key is not None:
            params["key"] = key
        return await self._client.call("server.database.get_item", params)

    async def post_item(self, namespace: str, key: str, value: Any) -> dict[str, Any]:
        """Store or update a value in the database

        Args:
            namespace: Database namespace
            key: Key to set
            value: Value to store
        """
        params: dict[str, Any] = {}
        params["namespace"] = namespace
        params["key"] = key
        params["value"] = value
        return await self._client.call("server.database.post_item", params)

    async def delete_item(self, namespace: str, key: str) -> dict[str, Any]:
        """Delete a value from the database

        Args:
            namespace: Database namespace
            key: Key to delete
        """
        params: dict[str, Any] = {}
        params["namespace"] = namespace
        params["key"] = key
        return await self._client.call("server.database.delete_item", params)

class AnnouncementsNamespace:
    """Moonraker announcement system

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def list(self, include_dismissed: bool | None = None) -> dict[str, Any]:
        """List current announcements

        Args:
            include_dismissed: Include dismissed announcements
        """
        params: dict[str, Any] = {}
        if include_dismissed is not None:
            params["include_dismissed"] = include_dismissed
        return await self._client.call("server.announcements.list", params)

    async def dismiss(self, entry_id: str) -> dict[str, Any]:
        """Dismiss an announcement

        Args:
            entry_id: Announcement entry ID
        """
        params: dict[str, Any] = {}
        params["entry_id"] = entry_id
        return await self._client.call("server.announcements.dismiss", params)

class WebcamsNamespace:
    """Webcam configuration

    Auto-generated from schema/moonraker_api.yaml.
    """

    def __init__(self, client: MoonrakerClient) -> None:
        self._client = client

    async def list(self) -> dict[str, Any]:
        """List configured webcams
        """
        return await self._client.call("server.webcams.list")

    async def get(self, name: str) -> dict[str, Any]:
        """Get a single webcam configuration

        Args:
            name: Webcam name
        """
        params: dict[str, Any] = {}
        params["name"] = name
        return await self._client.call("server.webcams.get_item", params)
