#!/usr/bin/env python3
"""Generate typed API bindings from the YAML schema.

Reads ``schema/moonraker_api.yaml`` and writes
``src/pymoonraker/api/_generated.py`` containing one class per namespace
with fully typed async methods for every endpoint.

Usage::

    python scripts/generate_bindings.py
"""

from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = ROOT / "schema" / "moonraker_api.yaml"
OUTPUT_PATH = ROOT / "src" / "pymoonraker" / "api" / "_generated.py"

HEADER = '''\
"""Auto-generated Moonraker API bindings — DO NOT EDIT.

Generated by scripts/generate_bindings.py at {timestamp}
from schema/moonraker_api.yaml.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pymoonraker.client import MoonrakerClient
'''

TYPE_MAP: dict[str, str] = {
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
    "Any": "Any",
    "list[str]": "list[str]",
    "dict[str, Any]": "dict[str, Any]",
    "dict[str, str]": "dict[str, str]",
    "dict[str, list[str] | None]": "dict[str, list[str] | None]",
    "list[FileItem]": "list[dict[str, Any]]",
    "list[FileRoot]": "list[dict[str, Any]]",
}

KNOWN_MODELS = {
    "PrinterInfo",
    "ServerInfo",
    "ConnectionIdentifyResult",
    "PrinterObjectList",
    "JobQueueStatus",
    "FileMetadata",
    "HistoryJob",
    "HistoryTotals",
}


def python_type(yaml_type: str) -> str:
    if yaml_type in KNOWN_MODELS:
        return "Any"
    return TYPE_MAP.get(yaml_type, "Any")


def snake_to_class(name: str) -> str:
    return "".join(word.capitalize() for word in name.split("_")) + "Namespace"


def generate_method(method_key: str, method_def: dict) -> str:
    rpc_method = method_def["rpc_method"]
    description = method_def.get("description", "")
    params = method_def.get("params", {})
    return_type = python_type(method_def.get("returns", {}).get("type", "Any"))

    sig_parts: list[str] = ["self"]
    body_params: list[str] = []
    doc_params: list[str] = []

    required_params = {k: v for k, v in params.items() if v.get("required", False)}
    optional_params = {k: v for k, v in params.items() if not v.get("required", False)}

    for pname, pdef in required_params.items():
        ptype = python_type(pdef.get("type", "Any"))
        sig_parts.append(f"{pname}: {ptype}")
        body_params.append(pname)
        doc_params.append(f"            {pname}: {pdef.get('description', '')}")

    if optional_params:
        for pname, pdef in optional_params.items():
            ptype = python_type(pdef.get("type", "Any"))
            sig_parts.append(f"{pname}: {ptype} | None = None")
            body_params.append(pname)
            doc_params.append(f"            {pname}: {pdef.get('description', '')}")

    sig = ", ".join(sig_parts)

    lines: list[str] = []
    lines.append(f"    async def {method_key}({sig}) -> {return_type}:")
    lines.append(f'        """{description}')
    if doc_params:
        lines.append("")
        lines.append("        Args:")
        lines.extend(doc_params)
    lines.append('        """')

    if body_params:
        lines.append("        params: dict[str, Any] = {}")
        for pname in body_params:
            if params[pname].get("required", False):
                lines.append(f'        params["{pname}"] = {pname}')
            else:
                lines.append(f"        if {pname} is not None:")
                lines.append(f'            params["{pname}"] = {pname}')
        lines.append(f'        return await self._client.call("{rpc_method}", params)')
    else:
        lines.append(f'        return await self._client.call("{rpc_method}")')

    return "\n".join(lines)


def generate_namespace(ns_name: str, ns_def: dict) -> str:
    class_name = snake_to_class(ns_name)
    description = ns_def.get("description", "")
    methods = ns_def.get("methods", {})

    lines: list[str] = []
    lines.append("")
    lines.append("")
    lines.append(f"class {class_name}:")
    lines.append(f'    """{description}')
    lines.append("")
    lines.append(f"    Auto-generated from schema/moonraker_api.yaml.")
    lines.append('    """')
    lines.append("")
    lines.append("    def __init__(self, client: MoonrakerClient) -> None:")
    lines.append("        self._client = client")

    for method_key, method_def in methods.items():
        lines.append("")
        lines.append(generate_method(method_key, method_def))

    return "\n".join(lines)


def main() -> None:
    with open(SCHEMA_PATH) as f:
        schema = yaml.safe_load(f)

    namespaces = schema.get("namespaces", {})

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    output = HEADER.format(timestamp=timestamp)

    for ns_name, ns_def in namespaces.items():
        output += generate_namespace(ns_name, ns_def)
    output += "\n"

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH} ({len(namespaces)} namespaces)")


if __name__ == "__main__":
    main()
